PhotoMania/config/routes.rb
PhotoMania::Application.routes.draw do
  
  get "users/home"

  root :to => 'users#home'
	match 'showcover/:data' => 'photo#showcover'
  	match 'users/signup' => 'users#signup'
	match 'users/home' => 'users#home'
	match 'users/authenticate' => 'users#authenticate'
	match 'photo/upload'=>'photo#upload'
	match 'users/remalb' => 'users#remalb'
	match 'photo/show1'=>'photo#show1'
	match 'photo/products'=>'photo#products'
	match 'photo/all'=>'photo#all'
	match 'users/photoframes' => 'users#photoframes'
	match 'photoframes' => 'users#photoframes'
	match 'photomugs' => 'users#photomugs'
	match 'tshirts' => 'users#tshirts'
	match 'users/logout' => 'users#logout'
  	match 'users/showall' => 'users#showall'
	match 'users/showalb' => 'users#showalb'
  	match 'photo/showpics' => 'photo#showpics'
  	match 'photo/rem' => 'photo#rem'
  	resources :photo
	resources :users

end

PhotoMania/app/models/album.rb
class Album < ActiveRecord::Base
  attr_accessible :aname
	belongs_to :user
	has_many :photos
end

PhotoMania/app/models/photo.rb
class Photo < ActiveRecord::Base
  # attr_accessible :title, :body
	belongs_to :user
	def image_file=(input_data)
    		self.filename = input_data.original_filename
    		self.content_type = input_data.content_type.chomp
    		self.binary_data = input_data.read
  	end

end

PhotoMania/app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :password
validates_presence_of :email
validates_presence_of :password
validates_uniqueness_of :email
has_many :albums
end

PhotoMania/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :set_cache_buster

  def set_cache_buster
    response.headers["Cache-Control"] = "no-cache, no-store, max-age=0, must-revalidate"
    response.headers["Pragma"] = "no-cache"
    response.headers["Expires"] = "Fri, 01 Jan 1990 00:00:00 GMT"
  end
end

PhotoMania/app/controllers/photo_controller.rb
class PhotoController < ApplicationController

	def showcover
		u=User.find(session[:user].id)
		a=u.find(params[:data])
		p=a.last
		pics=""
		if p
		pics='<img src="data:image/gif;base64,'+p.binary_data+'" width="200" height="200" id="'+"#{p.id}"+'" />'
		end
		send_data(pics,:type => "text/html");
	end
	def upload
		if params[:image_file].content_type=="image/jpeg" || params[:image_file].content_type=="image/png"
		if params[:aname]==nil || params[:aname]=="" || params[:image_file]==nil || params[:image_file].original_filename==""
			respond_to do |format|
			format.html {redirect_to(users_path)}
			end
		else
		@u=User.find(session[:user].id)
		a=params[:aname]
		input=params[:image_file]
		@b=@u.albums.find_by_aname(a)
		if(!@b)
		   @b=@u.albums.create(:aname=>a)
		end
		pic=@b.photos.new
		pic.filename=input.original_filename
		pic.content_type=input.content_type.chomp
		pic.binary_data=Base64.encode64(input.read)
		pic.description=params[:description]
		if pic.save
			note="saved"
		else
			note="not Saved"
		end
		respond_to do |format|
			session[:athome]=1
			format.html {redirect_to(users_path,:notice=>note)}
		end
		end
		else
			respond_to do |format|
			session[:athome]=1
			format.html {redirect_to(users_path)}
			end
		end
	end
	def show1 
  		@image_data = Photos.find(params[:id])
			if(@image_data)
  			@image = @image_data.binary_data
  			send_data(@image,:type=>@image_data.content_type,:filename => @image_data.filename, :disposition => 'inline')
			else
			respond_to do |format|
			format.html {redirect_to(root_path,:notice=>"No Image yet")}
			end
			end
	end
	def rem
		a=Photo.find(params[:data]).album_id
		@u=User.find_by_email(session[:user].email)
		@a=@u.albums.find(a)
		Photo.delete(params[:data])
		render :json => {"response" => a}
	end
  	def showpics
		@u=session[:user]
		@a=@u.albums.find(params[:data])
		data=@a.photos.all
		pics="<br/><div style='position:relative;top:50px;left:350px; font-size:40px;color:#3F5765;'>"+@a.aname+"</div>"
		data.each do |d|
			pics+='<img style="margin-top:50px;" src="data:image/gif;base64,'+d.binary_data+'" width="150" height="150" id="'+"#{d.id}"+'" /><button type="button" style="position:relative;bottom:138px;right:27px;font-size:10px;margin-top:150px;"onclick="del(this.value)" value="'+"#{d.id}"+'" id="'+"#{d.id}"+'">'+"X"+'</button>'
		end	
		send_data(pics,:type => "text/html");
	end
	def products
			session[:athome]=nil
			data='<a href="/photoframes"><div class="p" id="frames"><strong><font size="8">Frames</font></strong><br/>Frame your special moments!!<br/><br/><img src="/frame.jpg" alt="abc" align="middle" width="200" height="250" /></div></a>'+'<a href="/photomugs"><div class="p"><font size="8">Photo <strong>Mugs</strong></font><br/>Frame your special moments!!<br/><br/><img src="/mug.jpg" align="middle" alt="abc" width="300" height="250" /></div></a>'+'<a href="/tshirts"><div class="p"><strong><font size="8">T-Shirts</font></strong><br/>Frame your special moments!!<br/><br/><img src="/tshirt.jpg" alt="abc" align="middle" width="200" height="250" /></div></a>'
			send_data(data,:type => "text/html"); 
	end

end

PhotoMania/app/controllers/users_controller.rb
class UsersController < ApplicationController

def index
	if !session[:user]
		respond_to do |format|
			format.html {redirect_to(root_path)}
		end
	else
		respond_to do |format|
			session[:athome]=1
			format.html
		end
	end
end
def home
	respond_to do |format|
	if session[:user]==nil
	format.html
	else
	session[:athome]=1
	format.html {redirect_to(users_path)}
	end
	end
end
def signup
	a=params[:uname]
	b=params[:pwd1]
	c=params[:pwd2]
	if a==nil || b==nil || c==nil || a=="" || b=="" || c==""
		respond_to do |format|
			format.html {redirect_to(root_path)}
		end
	else
	if b!=c
		respond_to do |format|
			format.html {redirect_to(root_path)}
		end
	else
		p=User.new(:email=>a,:password=>b)
		if(p.save)
		session[:user]=p
		respond_to do |format|
			session[:athome]=1
			format.html {redirect_to(users_path)}
		end
		else
			respond_to do |format|
			format.html {redirect_to(root_path,:notice=>"Username already exists!")}
			end
		end	
	end
	end
end
def authenticate
	
	#User.create(:email=>"saransh",:password=>"saransh")
	a=User.find_by_email(params[:email])
	b=User.find_by_password(params[:password])
        respond_to do |format|
	if a && a==b
	session[:user] = a
	session[:athome] = 1
	format.html {redirect_to(users_path)}
	else
		format.html {redirect_to(root_path,:notice=>"Wrong or Non-permitted Details!")}
	end
	end
end
def showall
	@u=session[:user]
		@a=@u.albums.all
		pics="<br/><br/><br/>"
		@a.each do |data|
		dat=data.photos.all
		dat.each do |d|
			pics+='<img src="data:image/gif;base64,'+d.binary_data+'" width="150" height="150" id="'+"#{d.id}"+'" /><button type="button" style="position:relative;bottom:138px;right:27px;font-size:10px;" onclick="del(this.value)" value="'+"#{d.id}"+'" id="'+"#{d.id}"+'">'+"X"+'</button>'
		end	
		end
		send_data(pics,:type => "text/html");
end
def showalb
	@u=session[:user]
		@a=@u.albums.find(params[:data])
		data=@a.photos.all
		pics="<div style='font-size:20px;color:#3F5765;'>"+@a.aname+"</div>"
		data.each do |d|
			pics+='<img class="dr" src="data:image/gif;base64,'+d.binary_data+'" width="100" height="100" id="'+"#{d.id}"+'" draggable="true" ondragstart="drag(event)" />'
		end	
		send_data(pics,:type => "text/html");
end
def remalb
	a=params[:aname1]
	if a
	@u=session[:user]
	@a=@u.albums.find_by_aname(a)
	note="No such album!"
	if @a
	note="Album Removed!"
	x=@a.photos.find_all_by_album_id(@a.id)
	x.each do |y|
		Photo.delete(y.id)
	end
	Album.delete(@a.id)
	end
	end
	respond_to do |format|
	session[:athome]=1
	format.html {redirect_to(users_path,:notice=>note)}
	end
end
def logout
session[:user]=nil
session[:athome]=nil
respond_to do |format|
	format.html {redirect_to(root_path)}
	end
end
def photoframes
	if(session[:user]==nil)
		respond_to do |format|
			format.html {redirect_to(root_path,:notice=>"Please sign in to use the services.")}
		end
	else	
		respond_to do |format|
			session[:athome]=nil
			format.html 
		end
	end
end
def photomugs
	if(session[:user]==nil)
		respond_to do |format|
			format.html {redirect_to(root_path,:notice=>"Please sign in to use the services.")}
		end
	else	
		respond_to do |format|
			session[:athome]=nil
			format.html 
		end
	end
end
def tshirts
	if(session[:user]==nil)
		respond_to do |format|
			format.html {redirect_to(root_path,:notice=>"Please sign in to use the services.")}
		end
	else	
		respond_to do |format|
			session[:athome]=nil
			format.html 
		end
	end
end
def show
	respond_to do |format|
	redirect_to(root_path)
	end
end
end

PhotoMania/app/helpers/application_helper.rb
module ApplicationHelper
end

PhotoMania/app/helpers/photo_helper.rb
module PhotoHelper
end

PhotoMania/app/helpers/users_helper.rb
module UsersHelper
end

PhotoMania/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PhotoMania</title>
  <%= stylesheet_link_tag "login.css" %>
  <%= javascript_include_tag "PopupWindow.js" %>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
<% if session[:user]!=nil %>
<style>
table.menu
{
font-size:100%;
position:absolute;
visibility:hidden;
}
td.menu{background:#3F5765}
.menu a {color:white;}
</style>
<script type="text/javascript">
$(document).ready(function(){
	$("#product").click(function(){
		$("#notice").html("");
		$("#pic").html("");
		$("#cnt").load("/photo/products");
	});
	$(".p").live({mouseenter: function(){
		$(this).css('background-color', '#3F5765');
		$(this).css('color', 'white');
	
	},mouseleave: function(){
      		$(this).css('background-color', '#e5eecc');
		$(this).css('color', 'black');
   	}});

});
function showmenu(elmnt)
{
document.getElementById(elmnt).style.visibility="visible";
}
function hidemenu(elmnt)
{
document.getElementById(elmnt).style.visibility="hidden";
}
function showpics(a)
{
	$("#pic").load("/photo/showpics",{data: a});	
}
function showall()
{
	$("#cnt").html("");
	$("#pic").load("/users/showall");	
}
function del(a)
{
var r=confirm("Are you sure you want to remove this pic?");
if (r==true)
  {
	$.get('/photo/rem',{data: a}, function(dat){ 
      $("#pic").load("/photo/showpics",{data: dat.response});
    });
  }
}

function check(a,b) {
if(a.length==0)
{
alert("Please provide a file for upload!");
return false;
}
if((a.indexOf(".jpg")!=-1)||(a.indexOf(".png")!=-1)||(a.indexOf(".jpeg")!=-1) || (a.indexOf(".JPG")!=-1) || (a.indexOf(".PNG")!=-1))
{
if(b.length>0)
{
<% if session[:athome]==nil %>
var r=confirm("Are you sure you want to leave this page?");
if (r==true)
return true;
else
return false;
<% else %>
return true;
<% end %>
}

else{
alert("Provide an album name!")
return false;
}
}
else {
alert("Not a Valid format!");
return false;
}
}
function showalb(a)
{
	$("#photos").load('/users/showalb',{data: a});
}
function allowDrop(ev)
{
	ev.preventDefault();
}
function drag(ev)
{
	ev.dataTransfer.setData("Text",ev.target.id);
}
function remo()
{
<% if session[:athome]==nil %>
var r=confirm("Are you sure?");
if (r==true)
{
var p=confirm("Are you sure you want to leave this page?");
if(p==true)
return true;
else return false;
}
<% else %>
var r=confirm("Are you sure?");
if (r==true)
return true;
else return false;
<% end %>
}
</script>
</head>
<body>
<% note="" %>
<div id="modal" style="border:3px solid black; background-color:#3F5765;color:white; padding:25px; font-size:150%; text-align:center; display:none;">
	<input type="button" value="x" style="position:relative;bottom:39px;left:262px;font-size:10px;" onClick="Popup.hide('modal')"/>	
	<%= form_tag photo_upload_path, :multipart => true do %>
	<table class="men">
        <tr><td>Album name  : </td><td><%= text_field_tag 'aname', "" %></td></tr>
        <tr><td>Select Photo : </td><td><%= file_field_tag 'image_file' %></td></tr>
        <tr><td>Description : </td><td><%= text_field_tag :description,value=nil %></td></tr>
	</table>
        <%= submit_tag "Upload", :onclick => "return check(image_file.value,aname.value)" %>
	<% end %><br/>
        <h5>Album will be created if it does not exists!</h5>
	<h3>Your Albums:</h3>
	<% alb=Album.find_all_by_user_id(session[:user].id) %>
	<% alb.each do |a| %>
	<%= button_to_function a.aname, "document.getElementById('aname').value=this.value;", :id => a.id %>
	<br/>
	<% end %>
</div>
<div id="modal2" style="border:3px solid black; background-color:#3F5765;color:white; padding:25px; font-size:150%; text-align:center; display:none;">
	<input type="button" value="x" style="position:relative;bottom:40px;left:112px;font-size:10px;" onClick="Popup.hide('modal2')"/>	
	<%= form_tag users_remalb_path do%>
        <h3>Your Albums:</h3>
	<% alb=Album.find_all_by_user_id(session[:user].id) %>
	<% alb.each do |a| %>
	<%= radio_button_tag 'aname1', a.aname, :checked => true %>
	<%= label_tag a.aname %><br/>
	<% end %>
        <%= submit_tag "Remove", :onclick => "return remo();" %>
	<% end %><br/>
</div>
<div class="header">
		<ul>	<li class="left"><a class="hd" href="users">PhotoMania</a>
			<li class="left"><a class="hd" id="product">Products</a>
			<li class="right" onmouseover="showmenu('scripting')" onmouseout="hidemenu('scripting')"><%= session[:user].email %>
   			<table class="menu" id="scripting" width="220">
   				<tr><td class="menu">
<a href="#" onclick="Popup.showModal('modal');return false;">Upload</a></td></tr>
   				<tr><td class="menu">
<a href="#" onclick="Popup.showModal('modal2');return false;">Remove an Album</td></tr>
				<% if(session[:athome]==1) %><tr><td class="menu"><%= link_to_function "Show all Pics", "showall()", :id =>"showall" %></td></tr><% end %>
   				<tr><td class="menu"><%= link_to 'logout', users_logout_path %></td></tr>	
   			</table></li>
		</ul>
</div>
<% else %>
<script>
$(document).ready(function(){
	$("#product").click(function(){
		$("#notice").html("");
		$("#pic").html("");
		$("#cnt").load("/photo/products");
	});
	$(".p").live({mouseenter: function(){
		$(this).css('background-color', '#3F5765');
		$(this).css('color', 'white');
	
	},mouseleave: function(){
      		$(this).css('background-color', '#e5eecc');
		$(this).css('color', 'black');
   	}});

});
</script> 
</head>
<body>
<p id="notice" style="position:relative;top:70px;z-index:1"><%= notice %></p>
<div class="im" style="position:absolute;top:30px;"></div>
<div class="header">
		<ul>	
			<li class="left"><a class="hd" href="users">PhotoMania</a>
			<li class="left"><a class="hd" id="product">Products</a><%= form_tag users_authenticate_path, :class=>"abc" do %>
			<li class="left1">UserName:<%= text_field_tag :email,value=nil,options={:size => "10"} %>
			<li class="left">Password:<%= password_field_tag :password,value=nil,options={:size => "10"} %>
			<li class="left"><%= submit_tag "Log in" %><% end %>
			
		</ul>
</div>
<% end %>
<%= yield %>

</body>
</html>

PhotoMania/app/views/users/home.html.erb
<div id="sign" class="hidden12" style="opacity:.6;">
<%= form_tag users_signup_path do%>
<table class="men">
        <tr><td>Username  : </td><td><%= text_field_tag 'uname', "" %></td></tr>
        <tr><td>Password : </td><td><%= password_field_tag 'pwd1',"" %></td></tr>
        <tr><td>Confirm Password : </td><td><%= password_field_tag :'pwd2',"" %></td></tr>
</table>
<%= submit_tag "Signup", :onclick => "check(uname.value,pwd1.value,pwd2.value)" %>
<% end %>
</div>
<div class="container">
<div id="cnt">
<div class="signup" style="z-index:2;margin-right:10px;float:right;"><%= link_to_function 'Signup', 'if(document.getElementById("sign").className=="hidden12") document.getElementById("sign").className="visible12"; else document.getElementById("sign").className="hidden12";'%></div>
<%=image_tag("collage.jpg", :size => "1100x570") %></div></div>
<script>
function check(a,b,c)
{
	if(a.length==0 || b.length==0 || c.length==0)
	{
		alert("No Blank Fields are allowed!");
		return false;
	}
	else if(b!=c)
	{
		alert("Passwords do not match!");
		return false;
	}	
	else return true;
}
</script>
</body>
</html>

PhotoMania/app/views/users/index.html.erb
<div class="container">
	<div id="cnt">
		<div id="albums" style="float:left;" >
			<h2 style="color:#3F5765;">Your Albums</h2>
			<% alb=Album.find_all_by_user_id(session[:user].id) %>
			<% if alb.count==0 %>
			<h3>No <b>Albums</b> are there.</h3>
			<% end %>
			<% alb.each do |a| %>
			<img style='border:5px solid gray; padding:3px;' src='data:image/gif;base64,<%="#{a.photos.last.binary_data}"%>' width="100" height="100" /><br/>
			<%= link_to_function a.aname, "showpics(this.id)", :id => a.id %>
			<br/>
			<% end %>
			<%= notice %></p>
		</div>
	<font size="10" style="margin-left:30px;">Welcome <strong style="color:#3F5765"><%= session[:user].email %></strong>! check our new products.</font>
	</div>
	
<div id="pic"></div>	
</div>

PhotoMania/app/views/users/photoframes.html.erb
<div class="container" id="abc">
<div id="cnt">
	<div id="leftcontent">
		<ul>
			<hr>
			<li id="step1" ><hr>Select Frame<hr>
			<li id="step2"><hr>Select Photo<hr>
			<li id="step3"><hr>Complete Order<hr></li>
			<hr>
			<br/><br/>Select an album:<br/>
			<% alb=Album.find_all_by_user_id(session[:user].id) %>
			<% alb.each do |a| %>
			<%= button_to_function a.aname, "showalb(this.id);", :id => a.id %><br/>
			<% end %>
		</ul>	
	</div>
	<div id="rightcontent">
		<font size="8"><strong>Step </strong>1: </font><font size="6">Select the frame..</font><span id="button"></span><br/><br/>
		<div class="p1"><img src="/frames/1.jpg" width="150" height="200" id="1"></div>
		<div class="p1"><img src="/frames/2.jpg" width="150" height="200" id="2"></div>
		<div class="p1"><img src="/frames/3.jpg" width="150" height="200" id="3"></div>
		<div class="p1"><img src="/frames/4.jpg" width="150" height="200" id="4"></div>
	</div>
	<div id="photos"></div>
</div>
</div>
<script type="text/javascript">
document.getElementById("step1").className="highlight";
function ab()
{
	a=document.getElementById("place").innerHTML;
	if(a=="") return;
	document.getElementById("place").innerHTML="";
	document.getElementById("photos").innerHTML+=a;
	document.getElementById("button").innerHTML="";
}
function drop(ev)
{	
	
	ev.preventDefault();
	if(ev.target.id!="place")
	{
		alert("First remove the previous pic");
		return false;
	}
	
	var data=ev.dataTransfer.getData("Text");
	img=document.getElementById(data);
	img.height="240";
	img.width="200";
	ev.target.appendChild(document.getElementById(data));
	$("#button").html('<button id="complete">Place order</button>');
}
$(document).ready(function(){
	var imagesrc="";
	$(".p1").click(function(){
		$(".p1").css('background-color', '#e5eecc');
		$(this).css('background-color', '#3F5765');
		$("#button").html('<button id="step1.next">Next</button>');
		imagesrc=$(this).children("img").attr("src");
	});
	$("#button").click(function(){
		document.getElementById("step1").className="unhighlight";
		document.getElementById("step2").className="highlight";
		$("#rightcontent").html('<font size="8"><strong>Step </strong>2: </font><font size="6">Drop your photo on frame..</font><span id="button"></span><br/><br/><div id="box"><img src="'+imagesrc+'" align="center" width="250" height="300"/></div><div id="place" ondrop="drop(event)" ondragover="allowDrop(event)"></div><button onclick="ab()">Remove</button>');
		
		$("#rightcontent").css('position','fixed');
		
	});
	$("#complete").live("click",function(){
		$("#rightcontent").html('<font size="10">Thanks for using PhotoMania</font>');
		document.getElementById("step2").className="unhighlight";
		document.getElementById("step3").className="highlight";
	});
	

});
</script>

PhotoMania/app/views/users/photomugs.html.erb
<div class="container" id="abc">
<div id="cnt">
	<div id="leftcontent">
		<ul>
			<hr>
			<li id="step1" ><hr>Select Mug<hr>
			<li id="step2"><hr>Select Photo<hr>
			<li id="step3"><hr>Complete Order<hr></li>
			<hr>
			<br/><br/>Select an album:<br/>
			<% alb=Album.find_all_by_user_id(session[:user].id) %>
			<% alb.each do |a| %>
			<%= button_to_function a.aname, "showalb(this.id);", :id => a.id %><br/>
			<% end %>
		</ul>	
	</div>
	<div id="rightcontent">
		<font size="8"><strong>Step </strong>1: </font><font size="6">Select the mug..</font><span id="button"></span><br/><br/>
		<div class="p1"><img src="/mugs/1.jpg" width="150" height="200" id="5"></div>
		<div class="p1"><img src="/mugs/2.jpg" width="150" height="200" id="6"></div>
		<div class="p1"><img src="/mugs/3.jpg" width="150" height="200" id="7"></div>
		<div class="p1"><img src="/mugs/4.jpg" width="150" height="200" id="8"></div>
		<div class="p1"><img src="/mugs/5.jpg" width="150" height="200" id="9"></div>
		<div class="p1"><img src="/mugs/6.jpg" width="150" height="200" id="10"></div>
		<div class="p1"><img src="/mugs/7.jpg" width="150" height="200" id="11"></div>
	</div>
	<div id="photos"></div>
</div>
</div>
<script type="text/javascript">
function ab()
{
	a=document.getElementById("placemug").innerHTML;
	document.getElementById("placemug").innerHTML="";
	document.getElementById("photos").innerHTML+=a;
	document.getElementById("button").innerHTML="";
}
function drop(ev)
{	
	
	ev.preventDefault();
	if(ev.target.id!="placemug")
	{
		alert("First remove the previous pic");
		return false;
	}
	
	var data=ev.dataTransfer.getData("Text");
	img=document.getElementById(data);
	img.height="100";
	img.width="90";
	ev.target.appendChild(document.getElementById(data));
	$("#button").html('<button id="complete">Place order</button>');
}
$(document).ready(function(){
	var imagesrc="";
	$(".p1").click(function(){
		$(".p1").css('background-color', '#e5eecc');
		$(this).css('background-color', '#3F5765');
		$("#button").html('<button id="step1.next">Next</button>');
		imagesrc=$(this).children("img").attr("src");
	});
	$("#button").click(function(){
		document.getElementById("step1").className="unhighlight";
		document.getElementById("step2").className="highlight";
		$("#rightcontent").html('<font size="8"><strong>Step </strong>2: </font><font size="6">Drop your photo on mug..</font><span id="button"></span><br/><br/><div id="box2"><img src="'+imagesrc+'" align="center" width="200" height="300"/></div><div id="placemug" ondrop="drop(event)" ondragover="allowDrop(event)"></div><button onclick="ab()">Remove</button>');
		


		$("#rightcontent").css('position','fixed');
	});
	$("#complete").live("click",function(){
		$("#rightcontent").html('<font size="10">Thanks for using PhotoMania</font>');
		document.getElementById("step2").className="unhighlight";
		document.getElementById("step3").className="highlight";
	});

});
document.getElementById("step1").className="highlight";
</script>

PhotoMania/app/views/users/tshirts.html.erb
<div class="container"  id="abc">
<div id="cnt">
	<div id="leftcontent">
		<ul>
			<hr>
			<li id="step1" ><hr>Select T-Shirt<hr>
			<li id="step2"><hr>Select Photo<hr>
			<li id="step3"><hr>Complete Order<hr></li>
			<hr>
			<br/><br/>Select an album:<br/>
			<% alb=Album.find_all_by_user_id(session[:user].id) %>
			<% alb.each do |a| %>
			<%= button_to_function a.aname, "showalb(this.id);", :id => a.id %><br/>
			<% end %>
		</ul>	
	</div>
	<div id="rightcontent">
		<font size="8"><strong>Step </strong>1: </font><font size="6">Select T-Shirt..</font><span id="button"></span><br/><br/>
		<div class="p1"><img src="/tshirts/front/1.jpg" width="150" height="200"></div>
		<div class="p1"><img src="/tshirts/front/2.jpg" width="150" height="200"></div>
		<div class="p1"><img src="/tshirts/front/3.jpg" width="150" height="200"></div>
		<div class="p1"><img src="/tshirts/front/4.jpg" width="150" height="200"></div>
		<div class="p1"><img src="/tshirts/front/5.jpg" width="150" height="200"></div>
		<div class="p1"><img src="/tshirts/front/6.jpg" width="150" height="200"></div>
		<div class="p1"><img src="/tshirts/front/7.jpg" width="150" height="200"></div>
		<div class="p1"><img src="/tshirts/front/8.jpg" width="150" height="200"></div>
	</div>
	<div id="photos"></div>
</div>
</div>
<script type="text/javascript">
function ab()
{
	a=document.getElementById("placetshirt").innerHTML;
	document.getElementById("placetshirt").innerHTML="";
	document.getElementById("photos").innerHTML+=a;
	document.getElementById("button").innerHTML="";
}

function drop(ev)
{	
	
	ev.preventDefault();
	if(ev.target.id!="placetshirt")
	{
		alert("First remove the previous pic");
		return false;
	}
	
	var data=ev.dataTransfer.getData("Text");
	img=document.getElementById(data);
	img.height="80";
	img.width="80";
	ev.target.appendChild(document.getElementById(data));
	$("#button").html('<button id="complete">Place order</button>');
}
$(document).ready(function(){
	var imagesrc="";
	var imagesrc1="";
	$(".p1").click(function(){
		$(".p1").css('background-color', '#e5eecc');
		$(this).css('background-color', '#3F5765');
		$("#button").html('<button id="step1.next">Next</button>');
		imagesrc=$(this).children("img").attr("src");
		imagesrc1=imagesrc.replace("front","back");
	});
	$("#button").click(function(){
		document.getElementById("step1").className="unhighlight";
		document.getElementById("step2").className="highlight";
		$("#rightcontent").html('<font size="8"><strong>Step </strong>2: </font><font size="6">Drop your photo on t-shirt..</font><span id="button"></span><br/><br/><div id="box1"><img src="'+imagesrc1+'" align="center" width="300" height="300"/><img src="'+imagesrc+'" align="center" width="200" height="300"/></div><div id="placetshirt" ondrop="drop(event)" ondragover="allowDrop(event)"></div><button onclick="ab()">Remove</button>');
		



		$("#rightcontent").css('position','fixed');
	});
	$("#complete").live("click",function(){
		$("#rightcontent").html('<font size="10">Thanks for using PhotoMania</font>');
		document.getElementById("step2").className="unhighlight";
		document.getElementById("step3").className="highlight";
	});

});
document.getElementById("step1").className="highlight";
</script>